### ISSUE TITLE
给你提供个验证码识别思路

### ISSUE THREAD

**Issue by itning** [BlacAmDK/hxciSpider#1]
1.感知哈希算法
2.像素识别
先将验证码图片分隔存储,然后使用新获取到的验证码图片进行对比
学校验证码没有干扰,非常好识别

**Comment by BlacAmDK** [comment]
> 1.感知哈希算法
> 2.像素识别
> 先将验证码图片分隔存储,然后使用新获取到的验证码图片进行对比
> 学校验证码没有干扰,非常好识别

学校这个验证码由于不刷新不会变所以无论查多少只需要一开始手动输入一次，而且这个系统说不定什么时候就换了，这项目已经没修改的必要了。
